name: Create Tag in Private Repository

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: oneclickvirt/privatespeedtest
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create Tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          TAG="v0.0.1-$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag "$TAG"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update README.md
        run: |
          sed -i "s|go get github.com/oneclickvirt/privatespeedtest@.*|go get github.com/oneclickvirt/privatespeedtest@${TAG}|" README.md
        env:
          TAG: ${{ env.TAG }}

      - name: Commit and Push README.md
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README.md with new tag ${TAG}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          TAG: ${{ env.TAG }}
